lib/octopolo.rb, lib/octopolo/commands/pull_request.rb, lib/octopolo/github/pull_request_creator.rb, lib/octopolo/scripts/pull_request.rb, lib/octopolo/user_config.rb, spec/octopolo/github/pull_request_creator_spec.rb, spec/octopolo/scripts/pull_request_spec.rb, spec/octopolo/user_config_spec.rb
Adds the ability to edit the template for the pull request before it is
created.
This is toggled either via the user config or a command line flag.
Deploy Plan
-----------
* Merge this PR
* Release the gem
* Rejoice along with your other developers about how great this is
Rollback Plan
-------------
This is just so good, why would you want to roll this back?
QA Plan
-------
* Check out this branch
* Run `bundle exec op pull-request -e`
* Before it creates the PR, it should send you to your editor to update the
description
=> Update pull request with $EDITOR

lib/octopolo/github.rb, lib/octopolo/pull_request_merger.rb, lib/octopolo/scripts/deployable.rb, spec/octopolo/github_spec.rb, spec/octopolo/scripts/deployable_spec.rb
I took inventory of my OAuth tokens over the weekend and likely revoked the one that Octopolo was using. Upon trying to mark a branch as deployable, got the unhelpful "Sorry, can't mark as deployable, try again?" message. I discovered later it was because it was unauthorized, but decided to make this error message more helpful for the future (as many of the other commands, specifically anything to do with `PullRequestMerger`, rightfully try to tell you that you are unauthorized and should generate a new token). Refactored the deployable script to smell a little less, while I was at it. 
QA:
Honestly I bet @NickLaMuro has more of an idea what to look for with `deployable` if I botched anything up, but here are some standards...
See detailed specs I wrote for other behaviors.
=> More helpful errors / Refactor Deployable script

bin/op, octopolo.gemspec
Added a new `autocomplete_commands <boolean>` toggle to GLI, released in 2.13.0 (form this PR: https://github.com/davetron5000/gli/pull/211). This fixes the issue of partial commands doing bad things, such as `op deploy` -> `op deployable`. 
QA:
Easiest QA is just building this branch locally, installing it in a project, and trying `sync`. Should _not_ execute `sync-branch` but instead throw an UnknownCommand error.
=> Add new autocomplete_commands toggle; fixes #34

.gitignore, lib/octopolo/cli.rb, spec/octopolo/cli_spec.rb
Errors in CLI commands are currently being ignored silently.  This changes command errors to be raised and handled like other exceptions.  Errors will now be show to the user for review.
=> Errors from CLI commands should throw and exception

lib/octopolo/cli.rb, lib/octopolo/git.rb, spec/octopolo/cli_spec.rb, spec/octopolo/git_spec.rb
A command error should halt further actions, bubble up and return a non-zero from octopolo.  If something goes wrong with a command, we likely don't want to continue actions in an unknown state.  Also, for using octopolo in scripting it is useful to have a non-zero return code when something went wrong.
=> Command Errors Should Not Be Rescued

lib/octopolo/commands/new_deployable.rb, lib/octopolo/commands/new_staging.rb, lib/octopolo/dated_branch_creator.rb, lib/octopolo/scripts/new_deployable.rb, lib/octopolo/scripts/new_staging.rb, spec/octopolo/dated_branch_creator_spec.rb, spec/octopolo/scripts/new_deployable_spec.rb, spec/octopolo/scripts/new_staging_spec.rb
`new-staging` and `new-deployable` have a new flag to delete old branches of that type.  This behavior was already implemented but could only be enabled through a interactive prompt response.  These additions allow for non-interactive scripting usage without resorting to something like expect.
=> Adding delete flag to dated branch creation commands for non-interactive support

.travis.yml, lib/octopolo/commands/issue.rb, lib/octopolo/github.rb, lib/octopolo/github/issue.rb, lib/octopolo/github/issue_creator.rb, lib/octopolo/github/pull_request.rb, lib/octopolo/github/pull_request_creator.rb, lib/octopolo/renderer.rb, lib/octopolo/scripts/issue.rb, lib/octopolo/scripts/pull_request.rb, lib/octopolo/templates/issue_body.erb, octopolo.gemspec, spec/octopolo/github/issue_creator_spec.rb, spec/octopolo/github/issue_spec.rb, spec/octopolo/github/pull_request_creator_spec.rb, spec/octopolo/github/pull_request_spec.rb, spec/octopolo/github_spec.rb, spec/octopolo/scripts/issue_spec.rb, spec/octopolo/scripts/pull_request_spec.rb
Its like `pull-request` but for issues.
Upgraded octokit to fix bug with issue creation. 
Sharing some code between them since as far as the GitHub API is concerned, every pull request is an issue, but not every issue is a pull request.
`bundle exec octopolo issue` - verify issue creation
`bundle exec octopolo pull-request` - verify pr creation
=> Adding issue command to create issues.

lib/octopolo/pull_request_merger.rb
Use `.inspect` to log the message in addition to the class name.
Currently:
```
An unknown error occurred:  RuntimeError
```
=> Inspect error to get message + class name

lib/octopolo/git.rb, spec/octopolo/git_spec.rb
Deploy Plan
-----------
Does Infrastructure need to know anything special about this deploy? If so, keep this section and fill it in. **Otherwise, delete it.**
Rollback Plan
-------------
**If this pull request requires anything more complex (e.g., rolling back a migration), you MUST update this section. Otherwise, delete this note.**
To roll back this change, revert the merge with `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
QA Plan
-------
Provide a detailed QA plan, or other developers will retain the right to mock you mercilessly.
=> issue64 - improve git if_clean check

octopolo.gemspec
Rake is only need in development.
Making octokit less strict for greater compatibility.
=> Refine depdencies

lib/octopolo/commands/issue.rb, lib/octopolo/commands/pull_request.rb, lib/octopolo/commands/sync_branch.rb, lib/octopolo/config.rb, spec/octopolo/config_spec.rb
Features were added that cause eager loading of the configuration file for default command flags. This causes Octopolo to exit in error instead of providing help information and allowing you to set up Github auth for your user when you don't have a config file. That should be allowed.
This changes Octopolo to merely print a nice warning message saying it couldn't find your config file, allowing you access to those other functions. Also bubbles up messages from the Github wrapper which isn't so bad at all:
```plaintext
$ op view-pr
*** WARNING: Could not find .octopolo.yml or .automation.yml ***
An error occurred while getting the current branch: GitHub Repo is required
```
Fixes #76
r? @anfleene
=> Don't raise on missing config file

README.markdown, lib/octopolo/config.rb, lib/octopolo/git.rb, lib/octopolo/pull_request_merger.rb, spec/octopolo/config_spec.rb, spec/octopolo/git_spec.rb
This should resolve issue #52.
Rollback Plan
-------------
**If this pull request requires anything more complex (e.g., rolling back a migration), you MUST update this section. Otherwise, delete this note.**
To roll back this change, revert the merge with `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
* [Jira issue IS-4644](https://sportngin.atlassian.net/browse/IS-4644)
QA Plan
-------
Provide a detailed QA plan, or other developers will retain the right to mock you mercilessly.
=> Spring Cleaning IS-4644 Enable use of auto-merging resolver

lib/octopolo/jira/story_commenter.rb
Fixes Octopolo so that it doesn't bomb when Jira Story ID is invalid or if Jira's API fails.
Rollback Plan
-------------
**If this pull request requires anything more complex (e.g., rolling back a migration), you MUST update this section. Otherwise, delete this note.**
To roll back this change, revert the merge with `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
* [Jira issue kajsndkfa](https://sportngin.atlassian.net/browse/kajsndkfa) <== Proof that it works
QA Plan
-------
=> IS-4641-spring-cleaning-jira-bomb

lib/octopolo/commands/accept_pull.rb, lib/octopolo/commands/deployable.rb, lib/octopolo/github.rb, lib/octopolo/github/pull_request.rb, lib/octopolo/scripts/accept_pull.rb, lib/octopolo/scripts/deployable.rb, spec/octopolo/scripts/accept_pull_spec.rb, spec/octopolo/scripts/deployable_spec.rb
If a repository has status checks enabled, ensure that the all the checks have passed before:
- a pull request can be marked `deployable`
- a pull request can be accepted
=> Check PR status before marking deployable/accept-pull

.travis.yml, lib/octopolo/github.rb, spec/octopolo/github_spec.rb
What
Adding a `team_membership?` method to the Github module in order to apply restrictions on certain AutoMobile commands
Why
To restrict the use of new AutoMobile commands to certain users
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
* [Jira issue TEAM-4179](https://sportngin.atlassian.net/browse/TEAM-4133)
QA Plan
-------
I have tested this change in conjunction with AutoMobile's #154 using the auto_mobile_test repo with success, but I am not sure how to test this method while stand-alone.
=> Github team_member? method

octopolo.gemspec
What
Locking down public_suffix to 2.x which is a dependency of Octokit.
Why
3.x requires ruby 2.1 but OSX is still on 2.0 and we should maintain compatibility.
=> Fix Ruby 2.0 compatiblity

.travis.yml, lib/octopolo/pull_request_merger.rb, lib/octopolo/scripts/deployable.rb, octopolo.gemspec, spec/octopolo/scripts/deployable_spec.rb
What
> What are you changing?  Describe impact and scope.
Why
> Why is this being changed?  Provide some context that may help future developers understand the reasoning behind these changes. Quote and/or link to requirements, keeping in mind that JIRA/A-HA/etc links may not be available in the future.
Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
> Links to bug tickets or user stories.
QA Plan
-------
=> Fix merging into deployable

lib/octopolo/pull_request_merger.rb, spec/octopolo/pull_request_merger_spec.rb
Raises errors during PR merge errors, so that chained console commands do not run.
Deploy Plan
-----------
Does Infrastructure need to know anything special about this deploy? If so, keep this section and fill it in. **Otherwise, delete it.**
Rollback Plan
-------------
**If this pull request requires anything more complex (e.g., rolling back a migration), you MUST update this section. Otherwise, delete this note.**
To roll back this change, revert the merge with `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
QA Plan
-------
Provide a detailed QA plan, or other developers will retain the right to mock you mercilessly.
=> Fail on PR merge errors

lib/octopolo/jira/story_commenter.rb, lib/octopolo/version.rb, octopolo.gemspec
What
Upgrade the `jiralicious` gem to handle the new JIRA API
Why
JIRA has updated the APIs to use an API token for authentication instead of username & password (https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/). In order to use this though, we need to upgrade the version of the `jiralicious` gem to 0.5.0.
Deploy Plan
-----------
Once this change has been made and we deploy to Rubygems, we should update the `.octopolo.yml` configuration file in all repos that use `octopolo` to use the API token for the `jira_password` attribute. The `jira_user` in the config file must be a full email address instead of just a username.
Rollback Plan
-------------
* To roll back this change, revert the …
=> Upgrade jiralicious gem to handle the new JIRA API

lib/octopolo/commands/pull_request.rb, lib/octopolo/scripts/pull_request.rb, spec/octopolo/scripts/pull_request_spec.rb
What
Make `expedite`'s branch form more flexible. So take `iss-123_describe_branch`, but also accept `iss_123_describe_branch` as well.
Why
Because with all underscores is the form that _I_ use, so I want to be able to use expedite with my branches.
Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
> Links to bug tickets or user stories.
QA Plan
-------
```
git checkout -b iss_123_describe_branch
git pull origin iss_123_describe_branch
git commit --allow-empty -m "Empty commit"
git push
```
```
git checkout -b …
```
=> Make expedite's branch form more flexible

lib/octopolo/semver_tag_scrubber.rb, spec/octopolo/semver_tag_scrubber_spec.rb
What
See https://github.com/sportngin/octopolo/issues/129 for more information. Just simply rescue that error, and then `op tag-release` continues how a user would expect.
Why
This will fix https://github.com/sportngin/octopolo/issues/129.
Deploy Plan
-----------
> Does Platform Operations need to know anything special about this deploy? Are migrations present?
Rollback Plan
-------------
* To roll back this change, revert the merge with: `git revert -m 1 MERGE_SHA` and perform another deploy.
URLs
----
> Links to bug tickets or user stories.
QA Plan
-------
=> Fix bug where op tag-release on repo with no releases breaks
